In [3]:
import numpy as np

In [4]:
lines = []

with open("input.txt") as file:
    for line in file:
        lines.append(line.rstrip())


numpy_array = np.array([[int(num) for num in item.split('x')] for item in lines])
print(numpy_array)

[[20  3 11]
 [15 27  5]
 [ 6 29  7]
 ...
 [29  4  8]
 [21  2 22]
 [14 12  8]]


In [ ]:
## Test for smallest distance
arr = numpy_array
l = arr[:, 0]
w = arr[:, 1]
h = arr[:, 2]

find_min_distance = np.min((l+w, w+h, h+l), axis=0)

In [12]:
# print(find_min_distance)
total_length_ribbon = np.sum(find_min_distance+l*w*h)
print(f"""Wrong: {total_length_ribbon}""")


total_lenght_ribbon = np.sum(2*find_min_distance) + np.sum(l*w*h)
print(f"Right: {total_lenght_ribbon}")
## forgot the 2* of the min distance

Wrong: 3818626
Right: 3842356
